# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448e9733374f11098bc27d494a814ef63378ba4dbe7ee7c0e930543f93a337ce7c63de6dd7f079879d64c0d494daf5ade08f2321fe91a3d396e4c34cffdcd4c9

test:
  secret_key_base: 6b20b44a841cf0f392ba7c46d0a02c732b144309c3b69f84eac886613bd49886e3ffe358acf15d36969a8c162a66ae4ca7f216e07283ae5f9cb203d039056c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
